name: Sync Fork

on:
  schedule:
    - cron: "0 0 * * 0" # every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@e905b254d56ebb367514cd05fa96bf7516bd2a5a
        with:
          owner: delta-n
          base: sync-fork
          head: main
          merge_method: squash
          #auto_approve: true
          pr_title: "Sync Fork"
          pr_message: "This PR was created by the fork-sync GitHub Action to keep the fork up to date with the upstream repository."
