name: Sync Fork

on:
  schedule:
    - cron: "0 0 * * 0" # every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: gwolpert
          repo: azure-vaultwarden
          base: main
          head: main
          merge_method: merge
          pr_title: "Sync Fork"
          pr_message: "This PR was created by the fork-sync GitHub Action to keep the fork up to date with the upstream repository."
